name: card_submitter
description: "Credit Card Submitter - A Flutter app for capturing and managing credit card details with validation, filtering, and camera scanning."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Card Scanning
  card_scanner: ^1.0.2
  # UI
  cupertino_icons: ^1.0.8
  # State Management  
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  # Utilities
  get_it: ^7.6.4
  
  # Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  bloc_test: ^9.1.4
  
  # Code Generation
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  
  # Testing
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
